sudo: false
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
install:
  - pip install coveralls flake8 nose>=1.3.0
  - pip install -e .[all]
script:
  - flake8 .
  - python setup.py nosetests
  - python setup.py build_sphinx
  - container-transform container_transform/tests/fig.yml -v --input-type fig --output-type ecs
  - container-transform container_transform/tests/docker-compose.yml -v
  - container-transform container_transform/tests/task.json --input-type ecs --output-type compose
  - container-transform container_transform/tests/docker-compose.yml -v --output-type systemd
  - container-transform container_transform/tests/task.json --input-type ecs --output-type systemd
after_success:
  coveralls
